/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unijui.UI;

import br.edu.unijui.dao.ViagemImpl;
import br.edu.unijui.model.Viagem;
import br.edu.unijui.utils.FileUtils;
import br.edu.unijui.utils.XmlUtils;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucas
 */
public class DetalharViagens extends javax.swing.JFrame {
    
    ViagemImpl viagemImpl;
    List<Viagem> viagens;
    private PassageiroTableModel passageiroTableModel;
    
    public DetalharViagens() throws ClassNotFoundException, SQLException {
        viagemImpl = new ViagemImpl();
        initComponents();
        setComboBoxViagens();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxViagens = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePassageirosViagem = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalhesViagens = new javax.swing.JTextArea();
        jButtonConfirmarComboBox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonSalvarXml = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxViagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTablePassageirosViagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePassageirosViagem);

        jTextAreaDetalhesViagens.setEditable(false);
        jTextAreaDetalhesViagens.setColumns(20);
        jTextAreaDetalhesViagens.setRows(5);
        jTextAreaDetalhesViagens.setText("Detalhes da Viagem");
        jScrollPane2.setViewportView(jTextAreaDetalhesViagens);

        jButtonConfirmarComboBox.setText("CONFIRMAR");
        jButtonConfirmarComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarComboBoxMouseClicked(evt);
            }
        });

        jLabel1.setText("Escolha uma viagem para ver os detalhes:");

        jButton1.setText("HOME");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSalvarXml.setText("SALVAR EM XML");
        jButtonSalvarXml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarXmlMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConfirmarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonSalvarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarComboBoxMouseClicked
       Viagem viagem = (Viagem) jComboBoxViagens.getSelectedItem();      
       setDadosTabela(viagem);
       setDadosTextArea(viagem);
    }//GEN-LAST:event_jButtonConfirmarComboBoxMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Home homeTela = new Home();
        homeTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonSalvarXmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarXmlMouseClicked
         
        Viagem viagem = (Viagem) jComboBoxViagens.getSelectedItem();
        String xmlString = XmlUtils.objectToXml(viagem);
        FileUtils.saveXmlFile(xmlString, "./viagem.xml");
            
    }//GEN-LAST:event_jButtonSalvarXmlMouseClicked

    
    public void setComboBoxViagens(){
        jComboBoxViagens.removeAllItems();
        try {
            viagens = viagemImpl.getAllViagens();
            for(Viagem v: viagens){
                jComboBoxViagens.addItem(v);
            }         
        } catch (Exception ex) {
            System.out.print(ex.getMessage());
        }
    }
    
    public void setDadosTabela(Viagem viagem){     
        passageiroTableModel = new PassageiroTableModel(viagem.getListaPassageiros());
        jTablePassageirosViagem.setModel(passageiroTableModel);
    }
    
    public void setDadosTextArea(Viagem viagem){
        String textoDetalhesViagem = (
        "Origem: " + viagem.getOrigem() + "\n" +
        "Destino: " + viagem.getDestino()+ "\n" +
        "Avião: " + viagem.getAviao().getModelo()+ "\n" +
        "Número Passageiros: " + viagem.getTotalPassageiros() + "\n");
        
        jTextAreaDetalhesViagens.setText(textoDetalhesViagem);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirmarComboBox;
    private javax.swing.JButton jButtonSalvarXml;
    private javax.swing.JComboBox<Object> jComboBoxViagens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePassageirosViagem;
    private javax.swing.JTextArea jTextAreaDetalhesViagens;
    // End of variables declaration//GEN-END:variables
}
